name: CI Pipeline

on:
  push
    branches:
      - main

jobs: 
  bulid 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkuot@v3

    - name: set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'

      - name: install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run application
        run: python app.ny
